### ISSUE TITLE
GUI on Ununtu 12.04 

### ISSUE THREAD

**Issue by bojonfield** [OSCAAR/OSCAAR#167]
I am unable to get the OSCAAR GUI to run at all on my machine (Ubuntu12.04), after install I exit the directory as instructed and type; 

python -c "from oscaar import oscaarGUI"

but get the following error;

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/joe/ureka/Ureka/variants/common/lib/python2.7/site-packages/OSCAAR-2.0beta-py2.7.egg/oscaar/oscaarGUI.py", line 4, in <module>
    import wx
ImportError: No module named wx

Anybody able to help with this?
Thanks

**Comment by Mikea1985** [comment]
I realise this thread is old, but I figured others might have the same problem. 

The problem is that you are using Ureka. For those non-enlightened, Ureka is a fully packaged distribution of IRAF, python, ds9, xgterm and comes with python packages like matplotlib, numpy, astropy, pyfits and pyraf pre-installed. 
The problem is that when you have Ureka activated, calling python calls the python in your Ureka package, not your system's python. However, when you install wxpython, presumably using apt-get or other package manager, it gets installed for your system's python distribution. (If you've managed to install wxPython using pip, which I never have, you might need to run ur_setup BEFORE pip install wxPython; don't use sudo pip, as that will call your systems pip, not the ureka pip). If you need to use Ureka's python, you need to install wxpython into Ureka; I've never succeeded in this. I just cut python out of ureka, so when I call ur_setup, it uses my system python rather than ureka's python.
